#pragma once

#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 256
#define TARGET_FPS 60

#define RUSH_GRID_SIZE 6

#define RUSH_COLOR_BACKGROUND 32
#define RUSH_COLOR_BOARD 33
#define RUSH_COLOR_BLOCKED 34
#define RUSH_COLOR_GRID_LINE 35
#define RUSH_COLOR_PRIMARY_PIECE 36
#define RUSH_COLOR_PIECE 37
#define RUSH_COLOR_PIECE_OUTLINE 38
#define RUSH_COLOR_LABEL 39
#define RUSH_COLOR_WALL 40
